function plot(obj, qA, qB)
    options = {"show_arrows", false,...
                "unit_size", 0.25,...
               "show_arrow_labels", false,...
               "show_joint_labels", false,...
               "show_base_label", false,...
               "show_base_frame", false,...
               "show_task_frame", false,...
               "cyl_half_length", 0.125,...
               "cyl_radius", 0.05,...
               "show_task_label", false};
    
    diagrams.robot_plot(obj.kinA, qA, options{:});
    diagrams.robot_plot(obj.kinB, qB, options{:});
end