function plot(obj, qA, qB, qC, qD, qE, qF)
    options = {"show_arrows", true,...
            "unit_size", 0.25,...
           "show_arrow_labels", false,...
           "show_joint_labels", false,...
           "show_base_label", false,...
           "show_base_frame", false,...
           "show_task_frame", false,...
           "cyl_half_length", 0.125,...
           "cyl_radius", 0.05};

    diagrams.robot_plot(obj.kinA, qA, options{:}, link_color=diagrams.colors.red);
    diagrams.robot_plot(obj.kinB, qB, options{:}, link_color=diagrams.colors.green);
    diagrams.robot_plot(obj.kinC, qC, options{:}, link_color=diagrams.colors.blue);
    diagrams.robot_plot(obj.kinD, qD, options{:}, link_color=diagrams.colors.dark_red);
    diagrams.robot_plot(obj.kinE, qE, options{:}, link_color=diagrams.colors.dark_green);
    diagrams.robot_plot(obj.kinF, qF, options{:}, link_color=diagrams.colors.black);
end