function plot(obj, qA, qB)
% diagrams.setup;
% hold on
% view(2)
options = {"show_arrows", false,...
            "unit_size", 0.25,...
           "show_arrow_labels", false,...
           "show_joint_labels", false,...
           "show_base_label", false,...
           "show_base_frame", false,...
           "show_task_frame", false,...
           "cyl_half_length", 0.125,...
           "cyl_radius", 0.05};

diagrams.robot_plot(obj.armA.kin, qA, options{:});
diagrams.robot_plot(obj.armB.kin, qB, options{:});

% hold off
% diagrams.redraw;
end